<template>
  <section
    id="about-section"
    class="white-section"
  >
    <div class="container-fluid">
      <h1>About</h1>
      <p>
        This project is inspired by the
        <a href="https://www.police.uk/pu/your-area/greater-manchester-police/airport/?tab=CrimeMap">crime
          map</a>
        function of police.uk. And I found such information was useful for finding where to live when I was studying in
        UK.
      </p>
      <p>The frontend of the website is developed in Bootstrap and Vue.</p>
      <p>Map visulization is powered by Leaflet.js and its markercluster plugin.</p>
      <p>This static website is generated by Vue and hosted on Netlify.</p>
      <p>
        You can find the source code of the website on my <a
          href="https://github.com/YifeiLu-1/crimemap_ireland"
        >Github</a>.
      </p>
    </div>
  </section>
</template>

<script setup>

</script>
